apiVersion: v1
kind: Service
metadata:
  name: argo-server-nodeport
  namespace: argo
  labels:
    app: argo-server
spec:
  type: NodePort
  ports:
  - port: 2746
    protocol: TCP
    targetPort: 2746
    nodePort: 30746  # 可以自定义端口号 (30000-32767)
    name: web
  selector:
    app: argo-server 